export enum CityContextActionTypes {
  GET_CITIES = "GET_CITIES",
  ERROR_CITIES = "ERROR_CITIES",
  POST_CITY = "POST_CITY"
}

export enum EventContextActionTypes {
  GET_EVENTS_FROM_RADIUS = "GET_EVENTS_FROM_RADIUS",
  ERROR_EVENTS = "ERROR_EVENTS",
  POST_EVENT = "POST_EVENT"
}
